name: litxchange
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4 # Make sure to use the latest version suitable for your Flutter SDK
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.7
  firebase_database: ^10.1.0
  image_picker: ^0.8.4+4
  firebase_storage: ^11.6.8
  mailer: ^5.0.1
  google_sign_in: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/light-1.png
    - assets/images/light-2.png
    - assets/images/clock.png
    - assets/images/logo.png
