// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABrBRGIoR6To-P03prLXF0kWTe2twY3Qw',
    appId: '1:547250871756:web:5db62d6991bc74f51f1169',
    messagingSenderId: '547250871756',
    projectId: 'litxchange-76bcd',
    authDomain: 'litxchange-76bcd.firebaseapp.com',
    storageBucket: 'litxchange-76bcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlTaETiVuWg3th2h6mD81Wvl8u0Sun0fA',
    appId: '1:547250871756:android:ba0c981851fdcee91f1169',
    messagingSenderId: '547250871756',
    projectId: 'litxchange-76bcd',
    storageBucket: 'litxchange-76bcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55AcnOCDXSf6pZqMYaFNtt63suOc5rxM',
    appId: '1:547250871756:ios:d0c4f3066b5308cc1f1169',
    messagingSenderId: '547250871756',
    projectId: 'litxchange-76bcd',
    storageBucket: 'litxchange-76bcd.appspot.com',
    iosBundleId: 'com.example.litxchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55AcnOCDXSf6pZqMYaFNtt63suOc5rxM',
    appId: '1:547250871756:ios:838038861ea1dcec1f1169',
    messagingSenderId: '547250871756',
    projectId: 'litxchange-76bcd',
    storageBucket: 'litxchange-76bcd.appspot.com',
    iosBundleId: 'com.example.litxchange.RunnerTests',
  );
}
